### ISSUE TITLE
老大补充下详细命令可以吗

### ISSUE THREAD

**Issue by Lonely233233** [nv4d1k/streamlink-go#1]

**Comment by nv4d1k** [comment]
streamlink-go link -s huya 123321
streamlink-go link -s twitch eslcs
--proxy http://127.0.0.1:8080 if needed

**Comment by Lonely233233** [comment]
> streamlink-go link -s huya 123321 streamlink-go link -s twitch eslcs --proxy http://127.0.0.1:8080 if needed

thank you
