### ISSUE TITLE
Huaya douyin, opening it again will cut off the flow

### ISSUE THREAD

**Issue by Lonely233233** [nv4d1k/streamlink-go#3]
Huaya douyin hls stream will be interrupted when opened again

**Comment by nv4d1k** [comment]
streamlink-go will not caching any data, all the actions of extract streams will doing again when reopen

**Comment by Lonely233233** [comment]
> streamlink-go will not caching any data, all the actions of extract streams will doing again when reopen

I only found out yesterday that running streamlink go first, opening Douyin or Huaya live stream for the first time can play normally. After closing the player, opening the live stream again and playing for 2 minutes will cut off the stream

**Comment by nv4d1k** [comment]
Is there a way to reproduce this bug stably? I used it as a service on my router and didn't find any similar problems.

**Comment by Lonely233233** [comment]
> Is there a way to reproduce this bug stably? I used it as a service on my router and didn't find any similar problems.

I am using streamlink go. exe on the Windows system, and I don't know about other options. However, running streamlink go. exe through cmd on the Windows system works fine for the first time and requires me to close and rerun streamlink go. exe for later use. Otherwise, the stream will be interrupted in about 2 minutes

**Comment by nv4d1k** [comment]
try run streamlink-go with

streamlink-go.exe --debug --logfile debug.log
reproduce this bug and upload debug.log

**Comment by Lonely233233** [comment]
> try run streamlink-go with
> 
> streamlink-go.exe --debug --logfile debug.log reproduce this bug and upload debug.log

I will try downloading it again now to see if the previous exe is damaged

**Comment by Lonely233233** [comment]
I downloaded it again and now it seems normal again. Maybe it's because I used to download binary files, 
Damaged

**Comment by nv4d1k** [comment]
Ok. I'll close this issue. BTW, this repository will be archived. It has been merged into https://github.com/nv4d1k/live-stream-forwarder .
